[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "genreport"
version = "0.0.1"
description = "Markdown genealogy reports from GED files"
requires-python = ">=3.10"

[project.scripts]
genreport = "genreport.cli:main"
